<a href="https://colab.research.google.com/github/Tanvisharma31/CS-704_Deep-Reinforcement_Learning_Lab/blob/m/NumPy_Basics_For_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy** Basics For Deep Learning

In [36]:
#!pip install numpy

Basic array creation

In [37]:
import numpy as np
#create a 1d array
array_1d = np.array([1,2,3,4,5])
print("1D Array:",array_1d)

1D Array: [1 2 3 4 5]


In [38]:
#create a 2d array
array_2d = np.array([[1,2,3],[4,5,6]])
print("2D Array:\n",array_2d)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [39]:
#create an array with zeros
zeros_array=np.zeros((3,3))
print("Zeros Array:\n",zeros_array)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [40]:
#create an array with ones
ones_array=np.ones((3,3))
print("Ones Array:\n",ones_array)

Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Array Operations

In [41]:
#create two arrays
a=np.array([1,2,3])
b=np.array([4,5,6])


In [42]:
#addition
sum_array=np.add(a,b)
print("Sum:",sum_array)

Sum: [5 7 9]


In [43]:
#subtraction
diff_array=np.subtract(a,b)
print("Difference:",diff_array)

Difference: [-3 -3 -3]


In [44]:
#Multiplication
prod_array=np.multiply(a,b)
print("Multiply:",prod_array)


Multiply: [ 4 10 18]


In [45]:
#division
quotient_array=np.divide(a,b)
print("Quotient:",quotient_array)

Quotient: [0.25 0.4  0.5 ]


Matrix Multiplication

In [46]:
#create 2 matrix
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])


In [47]:
#matrix Multiplication
matrix_product=np.dot(a,b)
print("Matrix Product:\n",matrix_product)

Matrix Product:
 [[19 22]
 [43 50]]


Broadcasting

In [48]:
#create an array & a scalar
array=np.array([1,2,3])
scalar=2

In [49]:
#broadcasting
broadcasted_array=array*scalar
print("Broadcasted Array:",broadcasted_array)

Broadcasted Array: [2 4 6]


Statistical Operations

In [50]:
#create an array
data=np.array([1,2,3,4,5])

In [51]:
#mean
mean=np.mean(data)
print("Mean:",mean)

Mean: 3.0


In [52]:
#standard deviation
std=np.std(data)
print("Standard Deviation:",std)

Standard Deviation: 1.4142135623730951


In [53]:
#sum
sum=np.sum(data)
print("Sum:",sum)

Sum: 15


Reshaping Arrays

In [54]:
#create a 1d array
array=np.array([1,2,3,4,5,6])

In [55]:
#reshaping to 2x3
reshaped=array.reshape(2,3)
print("Reshaped Array:\n",reshaped)

Reshaped Array:
 [[1 2 3]
 [4 5 6]]


In [56]:
#reshaping to 3x2
reshaped_array=array.reshape(3,2)
print("Reshaped Array:\n",reshaped_array)

Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]


Element-wise Operations

In [57]:
#create Array
array_a=np.array([1,2,3])
array_b=np.array([4,5,6])

In [58]:
#Element-wise addition
add_result=array_a + array_b
print("Element-wise Addition:",add_result)

Element-wise Addition: [5 7 9]


In [59]:
#Element-wise Multiplication
multiply_result=array_a*array_b
print("Element-wise:",multiply_result)

Element-wise: [ 4 10 18]


Slicing & indexing

In [69]:
#create 2D array
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("array_2d:\n", array_2d)

array_2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
#accessing an element
element=array_2d[1,1]
print("Element at [1,1]:",element)

Element at [1,1]: 5


In [62]:
#accessing a row
row=array_2d[1,:]
print("Row:",row)

Row: [4 5 6]


In [63]:
#accessing a column
column=array_2d[:,1]
print("Column:",column)

Column: [2 5 8]


Creating Random Arrays

In [64]:
# Create a random array
random_array = np.random.rand(3, 3)
print("Random Array:\n", random_array)

Random Array:
 [[0.10630836 0.54534622 0.34157964]
 [0.49837601 0.60742334 0.3288937 ]
 [0.21665839 0.76879382 0.91433004]]


In [65]:
# Create a random integer array
random_int_array = np.random.randint(0, 10, (3, 3))
print("Random Integer Array:\n", random_int_array)

Random Integer Array:
 [[9 2 9]
 [3 6 1]
 [1 7 9]]


Stacking and Concatenating Arrays

In [66]:
#create two array
array_a=np.array([1,2,3])
array_b=np.array((4,5,6))

In [67]:
# Vertical stack
v_stack = np.vstack((array_a, array_b))
print("Vertical Stack:\n", v_stack)

Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [68]:
# Horizontal stack
h_stack = np.hstack((array_a,array_b))
print("Horizontal Stack:", h_stack)

Horizontal Stack: [1 2 3 4 5 6]
